/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 31.08.2026 19:23:50

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1520;
#else
constexpr int kTensorArenaSize = 496;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,156 } };
const TfArray<1, float> quant0_scale = { 1, { 0.97560375928878784, } };
const TfArray<1, int> quant0_zero = { 1, { -114 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[6] = { 10, 58, -65, 115, -41, 37, };
const TfArray<1, int> tensor_dimension1 = { 1, { 6 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0035005155950784683, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[6*10] = { 
  11, 59, -39, 35, -62, 6, -72, -22, -33, 10, 
  15, -105, -77, 52, 5, -22, -97, 72, 72, -116, 
  -50, 30, -127, -47, 48, 64, -38, -23, -4, -4, 
  -13, -85, 2, -5, 80, -99, -65, 10, -95, 23, 
  13, -60, 46, -96, -83, 54, -75, 55, 7, -33, 
  13, -38, -74, -41, -4, -77, 84, 11, -67, 48, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 6,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.01472033467143774, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -36, 80, 11, 26, 22, 4, 19, -63, -66, 5, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0041507203131914139, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  10, -44, -24, -28, 13, -21, 13, -38, -2, -82, -74, -1, 19, 28, 29, -31, -16, -9, -22, 7, 
  -23, -105, 29, 46, 27, -20, -80, -33, -29, -7, -3, -24, 19, -9, 13, 27, -28, 12, -14, -10, 
  -6, 32, -13, 39, -50, -21, 8, 15, -13, -113, -32, 10, -7, -2, 12, -22, 37, -33, -31, -25, 
  15, 1, 32, 13, -7, 13, -75, -32, -9, -11, 26, 4, -22, -35, -6, -31, -10, -21, 33, 26, 
  -14, 46, -26, -24, -44, 30, -46, 24, -29, -127, 38, 29, -7, 25, 26, -31, -1, 40, 23, 18, 
  -25, -8, -23, 26, -20, -64, 23, 38, -37, -49, 26, 26, -17, -22, -30, -21, -23, 27, -21, 1, 
  29, -7, -22, -57, 31, 41, 34, 7, -9, -44, 20, -7, -23, -18, 1, -4, 23, -20, -5, -11, 
  -8, 26, 1, 1, -31, -16, -43, -68, 36, -59, -54, 21, 22, -21, -61, 9, 8, -13, 4, 26, 
  15, 51, 1, -12, 3, -61, -38, -22, -9, 41, 37, -6, -2, -37, -99, 28, -45, 5, -15, -10, 
  15, -17, -4, -4, 34, 33, -30, -23, 24, -49, -21, -10, -23, -22, 15, -6, 3, 6, 1, 24, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.012172593735158443, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -1, 15, -9, 2, 3, -11, -6, -6, -1, 9, -3, -6, -1, -2, -10, -11, -10, -9, 0, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0094192987307906151, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*156] = { 
  0, 8, -9, 14, -1, 8, 4, -13, 6, -16, -1, 6, -17, -15, 6, 6, 4, 8, -11, -11, 14, -8, 12, 0, -22, 7, -10, -9, -23, -19, 0, 5, 10, -17, -19, 7, -12, 13, -2, -12, 0, -10, -16, -10, -17, 14, -8, 16, -13, -14, -4, -18, 6, -4, -15, 10, 12, 13, 17, 10, 6, -9, 1, -14, -4, -13, -2, 5, 14, -7, 3, -17, -13, -6, -5, -11, 12, 8, -7, 17, -12, -3, -7, 0, -4, 1, -20, -3, -15, -16, 9, -7, -4, 5, -5, -23, 17, 11, -15, -9, -3, -20, 3, 9, -8, -10, -7, -7, -18, -13, 12, 3, -1, 11, -9, 17, -7, 3, -15, 10, 1, 0, 1, 15, -21, -5, 11, 0, 14, -5, -19, -11, 18, 1, 12, -11, 0, 17, -6, 0, 8, -2, -14, -15, -5, -1, -9, 6, -15, -12, -10, 10, -5, 12, 6, -6, 
  -14, -55, -4, 5, -22, 19, 17, 12, 3, 9, -28, -10, -23, 23, -76, 18, 20, -1, 53, 22, 39, 43, 66, 37, 51, 46, -5, 5, -15, 5, 12, 28, 24, 35, 23, -7, -20, -11, -6, -10, -1, -24, 30, 17, 21, 4, 24, -4, 9, 7, -11, 4, -1, -18, -31, -3, -1, 22, 20, -13, -1, 14, -6, -3, -3, -4, 40, -57, 25, 8, 25, -6, 13, 0, 4, 17, -4, -10, -13, -53, 4, -5, 3, 0, 5, -9, -20, -31, -15, -22, -15, 37, 27, -1, 13, 22, -3, -16, -4, -27, -5, 5, -10, -5, -6, -20, 32, -3, -9, 4, -2, -25, 3, -11, -24, -4, -17, 1, -49, -5, 8, -31, 4, -3, 13, 3, 3, 11, -12, 22, 3, 3, 2, 7, 29, 23, -2, 2, 4, 21, -7, 14, 8, -7, -35, 7, 17, -2, 5, 0, 0, 3, 0, 2, 2, 21, 
  -1, -24, -2, -27, -6, 10, 22, 30, 32, 15, -2, 17, 3, 0, -42, 9, 2, 8, 26, 23, 33, -4, 16, -3, 8, 9, 8, 1, -7, -25, -15, 15, 19, -20, -1, 0, -10, 3, 15, -16, 2, 2, -9, 21, 5, -9, -15, -21, -1, -9, 3, -10, 3, 7, 8, -23, -8, -4, -6, -12, 9, -14, -14, -5, -15, -6, -13, -7, -7, -5, -3, -29, -9, 11, -9, -19, -21, 3, -21, 61, 6, -9, 29, -2, -3, -2, -13, -6, -25, -7, -24, 59, -72, 31, 3, -19, 30, 39, 42, 49, 26, 40, 46, 41, -20, 32, 11, -2, -27, -10, -13, 3, -11, -30, -29, -33, -7, 5, -38, 25, -10, 23, 13, -19, 12, 8, -4, 4, -25, -11, 6, -94, 18, -7, -18, 1, -10, 9, 7, 0, -12, 7, 8, 6, 2, 7, -12, 25, -14, -2, 4, -13, -10, -3, 4, 14, 
  -31, 54, 5, 32, 48, 12, 7, 29, 16, -14, 14, 17, 8, 68, -8, 2, -12, -11, 34, 46, 14, 42, 21, 22, 40, 43, -8, 5, 37, 9, -17, 22, 42, 10, 28, 19, 32, -4, 18, 4, -33, 24, -1, 14, 26, -2, 8, -6, 15, 12, -9, 4, 6, -5, 10, -6, 10, -14, 3, 6, 23, 14, 26, 21, -5, -14, -13, 9, -4, 4, 18, -1, -1, -4, 14, 16, 6, 28, 14, 69, -21, 7, 1, 6, 7, -8, 11, 0, 27, 1, 20, 6, -28, 19, 12, -15, 4, 21, 40, 30, 29, 34, 48, 26, -16, 46, -6, -1, 10, 12, -11, 14, 12, 26, 16, 28, -10, -7, 29, -15, -14, 22, 4, 9, -11, 6, 4, -7, 9, 12, -6, 10, -5, 14, -12, -7, -9, 7, 6, 16, 15, 14, 8, -5, 7, -8, -1, 4, -5, -13, -4, -10, 16, 18, -11, 7, 
  10, 8, 6, -30, -41, -21, 10, -10, -14, 7, -9, -1, -15, -22, 6, 1, 8, 8, -10, -13, -11, 7, -16, -16, -19, -16, 3, 1, -14, -23, -9, -19, 9, -20, -12, -15, -10, -22, -1, -1, 3, -5, -6, 3, 0, -23, 5, 3, -13, 4, 4, 5, -23, -13, -8, 22, 2, 2, 5, 0, -26, -27, 6, 6, -10, 3, -24, 25, -14, -3, -17, -12, -3, -7, -6, -4, -18, -17, -13, -2, 28, -16, 13, -9, 14, -3, 10, -6, 13, -1, -4, 1, 6, 18, 6, 3, 6, -7, -32, -33, -15, -30, -6, -19, 21, -27, -5, -2, -7, 14, -4, 7, -4, 6, 13, 4, -1, -6, 10, 14, 16, 2, -10, 2, -9, 11, 29, -3, 4, 20, -5, -2, 14, -2, 2, -2, 14, 16, -10, 22, 14, 12, 20, -5, 18, -14, 13, 9, -19, -17, -2, 10, -5, -12, 11, 21, 
  6, -19, -28, -16, -31, -12, 1, 26, 2, 19, -2, 9, -1, -45, 26, 10, -26, 4, -27, -18, -28, -34, -21, -28, -5, -23, -15, -13, -10, 10, -17, -9, 0, -17, 1, -26, 8, -11, 7, 11, 11, -4, -20, -8, -1, -26, -18, -16, -4, 10, 14, -6, 6, -50, 3, 0, -21, -6, 7, -1, 3, -19, 11, -16, -6, 0, 7, 7, 1, -16, 11, -17, 6, -20, -25, -17, -8, -8, 7, 4, -2, 7, 9, -4, -11, -9, 8, 8, 22, 8, 13, -10, -14, 12, -7, -8, -21, 3, 3, 23, 5, 24, 28, 2, -2, -19, 28, -26, -8, -2, -8, -2, 11, 19, 25, 16, 30, -2, -10, 2, -31, 8, -20, -2, -2, 13, -5, -10, -11, -22, -2, -5, -1, -16, 4, 11, 6, -15, 15, 18, 9, -2, -1, -5, 20, 1, 6, 7, 7, -18, 7, -4, -3, -25, 4, -8, 
  1, 120, 12, -12, -8, -24, -8, 8, -6, 3, 3, 3, 11, 16, 54, -58, -7, 2, 12, 7, -21, -12, -24, 6, -11, -9, 10, 3, 3, 4, 15, -22, -7, -9, -22, 4, -21, 8, -10, 13, 27, -56, -6, -5, -13, -21, 13, -16, -6, -9, -16, 11, -11, -8, -8, -1, 18, 12, 8, -9, -14, 0, 12, -11, 8, 7, -58, 7, -27, -32, 2, 18, -6, 9, 6, 11, 9, 15, 9, -1, -3, 6, -6, 7, 6, 9, 32, 21, 7, 5, 5, 2, 8, 0, -14, -27, 3, 12, 6, 28, 11, 16, 24, 17, 23, 10, -6, -20, -17, 5, 14, 26, 35, 1, 29, 19, 36, -10, 3, 1, -18, 11, -17, 2, 0, -11, 7, 16, 4, -10, 0, -37, 6, 4, 17, 14, -17, 9, 15, 21, 9, 10, -6, -11, 9, 10, 11, -7, 12, 12, -10, 19, 3, 22, -3, -10, 
  -1, 2, -13, 17, 34, -10, 2, 5, -8, 11, -6, 16, -12, 16, -7, 2, -14, -8, -29, 17, 17, -8, 1, 3, 6, 21, -4, -10, -12, -8, -2, 22, 9, 1, 6, -5, 8, 19, 26, -3, 5, 11, 5, 7, 0, -3, 4, -14, -8, 11, -10, -2, -5, -9, 2, -16, -2, 8, 12, -19, -9, -3, 19, -8, 17, 3, 5, -9, -14, 29, -19, 3, -1, 7, 0, 2, -6, 13, -15, -17, 27, -31, -14, -7, 2, -19, 11, 11, 20, -2, 2, -74, 97, -35, -9, 23, -38, -49, -30, -18, -37, -32, -38, -56, 13, -60, -9, -11, 45, -8, -14, -13, 12, 20, 30, 6, 26, -4, 30, -8, -11, -1, -7, -24, 2, 5, -14, -16, -4, -3, 4, 95, -22, 1, -9, 9, -12, -10, -5, -6, -3, 9, 10, 10, 21, 15, -12, -37, 9, -2, 4, -14, -4, 6, 6, 0, 
  10, 18, 11, -4, -17, 11, -3, -12, -2, -4, 1, 11, 10, -7, 4, -9, 7, -9, 18, 3, 17, 12, 16, 7, 11, 11, 13, -2, 15, -17, 10, -19, -3, -1, -16, -6, -17, 15, -13, 1, -10, -9, -18, -8, -17, 5, -7, -3, -10, 5, -18, -19, 18, -11, 10, 8, 2, 8, -3, -8, 11, -5, 15, -8, 0, -19, 17, 13, 11, -10, -9, -6, 3, -16, -6, -18, -14, -9, -11, 17, -9, -11, -15, -9, 15, 5, 0, 7, 11, 11, 1, -18, -16, -4, 14, -2, 17, 4, 8, -10, -13, -11, -8, 9, 2, 13, -4, 2, 4, -2, -9, 12, 3, 9, 15, 18, 7, -12, 15, -5, 13, 14, 0, -6, 9, -18, 3, 18, -18, 14, -18, 14, -20, -6, -14, -1, -14, 16, 4, 15, 15, -2, 12, -11, -15, 3, 7, -14, -18, -12, 16, 10, -11, -13, -10, 11, 
  -13, -27, -25, 9, 2, 22, -11, -11, -19, -31, -33, -33, -34, 7, -36, -17, 4, 13, 35, 12, 18, 34, 20, 38, 33, 31, 9, -24, -25, 26, 25, 8, -5, 2, 16, 3, 1, 3, -15, 8, 26, -10, 0, 14, 3, -8, 24, 20, 29, -2, 23, 31, -19, 0, -14, 13, 5, 12, -9, 14, -8, -1, -2, 26, 13, -11, -15, -27, -3, 22, -5, 20, 25, 9, 5, -6, 26, 3, -27, -34, -5, 31, 5, -8, -13, 15, -14, -14, 4, -3, 6, 15, -17, -8, 9, 20, 14, -3, 4, 1, 39, -2, 11, 3, -5, -15, -19, 3, 23, 12, 9, -9, -19, -7, 9, 10, 5, -2, 20, -17, 24, -11, -3, 22, -7, 11, 16, -4, -7, 9, -8, -8, -8, 11, 14, 15, 22, 7, 9, -10, 21, -4, 13, -1, -31, -9, 29, 12, -10, 4, -10, -12, -1, -9, 24, -11, 
  8, 22, -24, -14, -2, -7, 22, 8, 5, 10, -7, 18, 17, -16, 41, -41, -4, 3, 15, 15, -3, 20, -4, 21, 26, 1, -4, -4, -9, 21, 5, 10, 1, 25, 40, 37, 15, 7, 8, 10, 44, -16, -3, -3, -2, 20, 12, -4, 27, 23, 12, 5, -19, -24, 3, 17, -8, -5, 7, 0, 10, 12, 21, 20, 14, -8, -11, -9, 8, 17, 17, 11, 7, 3, 13, 29, 20, 3, 0, -23, 29, -20, -10, -20, -12, 9, -7, 4, -5, -9, 2, -19, 79, -36, 6, 28, -32, -22, -47, -29, -18, -37, -28, -37, 14, -78, 20, -10, 40, -1, -8, -2, 6, 12, -13, 9, -3, 7, 53, -6, -11, -19, -16, -22, 9, 5, -17, 1, 6, -19, 3, 89, -4, -7, 34, 2, -11, -24, 9, 5, -11, -17, -12, 0, -15, -11, -9, -22, 6, -11, -5, 6, 6, 13, -14, -14, 
  -17, -5, -4, -7, -2, -44, 4, -16, 8, -12, 16, 13, 6, 13, 15, 13, -18, -6, -8, -8, -3, -3, 26, 1, 12, 6, 1, 15, 13, 2, -2, -8, -8, 1, 12, 2, -9, 12, 12, 0, 17, 16, -1, -22, -27, -16, -5, 3, -19, -7, -17, 8, 4, 0, 11, 3, 12, -13, -5, -22, 11, 8, 3, -5, 14, -2, 1, 1, -13, -4, -27, -3, -12, -17, 9, -3, 2, 11, 11, -78, -11, 8, -31, -18, -24, -21, -14, 6, -2, 11, 11, -62, 58, -40, 5, 23, -18, -20, -38, -45, -35, -46, -23, -28, 21, -21, -18, 18, 10, -20, -13, -1, 7, 7, -13, -8, -16, 5, 34, -12, 12, 5, -4, -13, -7, -9, -13, -17, 16, 12, -6, 58, -29, 2, 10, 1, -22, 9, -14, 7, -2, 1, -4, 9, 4, -22, -12, -31, -17, -15, 7, -17, -8, -4, -9, 1, 
  -10, -17, -2, -7, 11, -18, -12, -18, -16, 9, -4, -17, 5, 9, -5, 12, 1, -6, 15, -6, 8, 10, -12, 12, 10, -5, 0, -8, 14, -5, -7, 4, -19, 17, 12, 12, 15, -13, -16, -14, -1, 1, -16, -10, -20, -9, 16, 9, -4, 18, 11, -18, -21, 5, -15, -20, -12, 4, -5, 7, -8, -15, -16, 11, 2, 3, 11, 5, 0, 13, -2, -10, 7, 11, 4, -20, -9, 13, -18, -18, 1, 7, 15, 11, 16, 13, -18, -12, 0, 11, -14, 16, 4, 1, -14, -18, 6, 1, 11, -5, -14, 10, 8, 5, -2, -16, -1, 14, 8, 2, -2, -7, 0, -10, -13, 2, -10, -8, 17, 8, 10, -3, 5, -12, 5, 6, -20, 9, -12, 15, -3, 10, 14, -2, 6, 16, 9, -2, 13, 18, 10, 3, 14, -7, -7, -6, -20, 12, -8, -20, 3, -15, -2, 5, -3, 17, 
  -1, -59, 3, 5, 40, 20, -15, 20, -3, 4, 3, 3, 14, 14, -25, -5, -16, 12, -10, 1, -3, -1, 16, 9, 7, -2, -17, 10, 6, 1, 15, -17, -10, -15, 1, 6, 7, -2, 13, -10, 15, 25, 19, 9, 15, -9, -1, 10, 19, 12, 7, 10, -15, -17, 13, -2, 31, 12, 8, -4, -1, -7, -4, -15, 12, 8, 38, 18, 9, 38, -19, -7, 9, -6, 6, -17, -13, -12, 1, -25, -8, 5, -17, -4, 9, 1, 10, 14, -2, -20, -1, -8, -27, 13, -21, -25, -16, 15, -3, -12, 0, 14, 2, -16, -26, 18, 0, -5, -14, 0, 9, -21, -15, 2, -14, 6, 6, -19, -3, -20, -3, -14, -9, -8, 15, 2, -17, 14, 5, 15, -16, -7, 6, -4, -27, -18, 11, -7, -9, 13, 18, 0, 11, -27, -14, 5, 8, -12, 10, 16, -9, -13, -16, -15, -9, 16, 
  24, -124, -22, -10, -14, -4, -5, 21, 20, 24, 34, -7, -9, 0, -52, 36, -23, 6, 6, -17, 27, 33, 11, 29, -5, 3, -17, -44, 8, -16, 6, -15, -14, 20, 8, -7, -9, 11, 16, -16, -28, 33, -21, 36, -13, 3, -12, -16, -23, -12, -9, 4, 10, -26, -26, -27, 1, -7, 14, -12, 1, 9, -11, 16, 3, 4, 65, 19, -3, 30, -8, -21, 9, -16, 9, 1, -15, -4, -13, -16, -2, 4, 9, -18, -14, -20, 6, 4, -15, 10, -8, 1, 3, -5, -17, 8, -4, -14, -4, 6, -29, 10, -20, 7, -30, -39, 10, -22, -11, -15, -20, -13, 6, 3, -22, 5, 22, 4, -10, 7, -19, -13, -2, -12, -15, -16, -2, 17, 17, -13, 4, -7, -6, -7, 13, 10, 21, 10, -12, 19, -2, 13, -2, -11, 7, 1, -2, -23, 6, 9, -11, -19, 10, 7, 5, -16, 
  -7, 44, -18, -27, -22, -6, -14, -7, -2, -2, -8, 1, -15, 1, 33, -10, -8, -4, -4, 1, -27, 6, -25, 2, -2, -6, -22, -30, -13, -23, -8, -19, -18, -1, -13, -9, -11, -27, -2, 4, 14, -26, -5, -21, 2, -23, -29, -16, -25, 1, -4, -13, 7, 8, 10, -22, 3, -2, -25, 6, -10, -22, -7, -18, -7, 1, -15, -10, -11, -1, -26, 6, 6, 8, -1, 5, -17, -4, 12, 25, -25, -18, 0, 15, 28, 25, 14, 22, 23, 29, 11, 15, 8, -7, 10, 4, -1, 25, 24, 23, 28, 31, 32, 8, 12, -4, -4, -2, 12, -6, 18, -2, -5, 17, 24, 4, 9, -19, 10, -8, -20, -5, -7, -9, 6, -3, -9, -6, -2, -12, -9, -6, -1, 8, -16, -16, -17, -12, -5, -4, -18, -1, -15, -2, 16, -3, 9, -6, -10, -22, 3, -14, -15, 8, 7, 3, 
  1, -23, 10, -17, -8, -6, -6, -12, 13, -8, -8, 3, 17, 2, 6, -16, -25, -24, 8, -7, -15, -13, 1, -7, 4, -7, -12, -15, -11, 0, -6, -6, 11, -18, -10, -13, 4, -17, -8, -8, 4, -4, -2, 11, -11, -26, 4, -28, -12, -17, -8, -12, 2, -10, -8, -26, -11, -14, 2, -23, -23, 7, -21, -8, -23, 7, -20, -4, -12, -4, -23, -15, -21, 7, 4, 0, -19, -5, -17, 33, 0, 8, -26, -11, -5, 13, 2, -6, 21, 0, 7, 43, -27, 7, -18, -42, 11, 14, 40, 21, 25, 28, 26, 29, -9, 32, 14, 2, -28, -21, 3, -3, 7, -25, -23, -1, -9, 8, -22, 1, -7, -15, -20, -8, 11, -4, -10, -24, 9, 9, -3, -28, 0, -14, -31, -9, 8, -19, 12, -23, 8, -12, 4, -9, 0, -4, 8, 9, -12, -7, -18, -11, 6, 0, -9, -15, 
  -16, 20, 3, 11, 24, -33, -18, 9, 5, -6, -3, 19, -9, -22, 23, 2, -24, 3, -15, -28, 1, -14, -10, 14, -8, -21, -12, 0, -7, -16, -2, -19, -6, 17, 12, 30, 29, 3, 26, -16, -7, 2, 0, -23, -7, -20, -4, 16, -14, 8, -8, -11, 6, 2, 8, -24, 19, -23, -8, -11, 6, -14, 13, 20, -1, 3, 10, 3, -4, -5, 2, -10, 12, 13, 6, 0, -17, -14, 10, -55, -5, -33, -46, -10, 0, 9, -13, -2, 1, 4, -3, -49, 81, -53, 16, 35, -34, -56, -36, -80, -47, -68, -72, -86, 2, -90, -27, 21, 32, -29, -30, -18, 10, 0, -11, 9, 14, 17, 44, -26, -20, 7, -6, 2, -11, -1, 0, 8, 10, 9, -2, 127, -19, 15, 13, -13, 3, -1, -8, -15, -27, -26, -25, 8, 5, 4, -10, -20, 7, -12, -2, 4, -30, -24, -5, -16, 
  -16, -5, 10, -19, 9, 2, -12, -2, -1, -7, -18, -7, -16, -13, -14, -10, 1, -11, -10, 7, -9, 16, -10, 15, -8, -17, -1, -5, -17, -13, 9, -8, -12, -17, 19, 15, 5, -13, -15, -6, -14, 4, -11, 10, 1, -3, 19, 4, -15, -17, 1, -16, 9, -11, 12, -13, -12, -12, -5, 14, -6, -10, -13, 15, 9, -10, 17, -15, 1, 17, 12, 10, 14, -9, -18, 6, 17, 3, -6, 7, 5, 8, 17, -1, 9, 3, 16, 2, -1, -15, -18, 15, 12, -6, -14, -14, 10, 4, 18, -12, -19, 19, 4, 2, -9, 0, -10, -14, 1, 11, -13, 2, -19, -10, -11, -14, 9, 8, -17, -17, 16, -11, -5, 3, 5, 18, -4, -8, 1, 1, -17, -9, 1, -1, -3, -10, 5, 18, -8, 6, 13, -6, -3, -8, 16, 14, 5, 6, -3, -5, -1, 7, 15, 8, 0, -9, 
  -1, 14, 1, -10, -3, -7, 5, -3, 13, 13, -16, 15, 13, 0, 0, -8, -1, -16, -10, 5, -7, -17, 15, -15, -1, 1, -13, -8, 7, 15, -13, 2, 16, -12, 1, 6, -18, 4, 1, -4, -12, -13, 5, 11, 0, -16, -18, 5, -2, 0, 4, 8, -17, 6, 9, -10, 10, -16, -13, 15, -15, 12, -14, 6, -15, -3, -3, -13, -14, -11, -19, 12, -6, -3, -5, 6, -16, -19, -17, -9, 14, -1, 0, -16, -4, 7, 17, -2, 6, 0, -18, 3, -14, -5, 6, -16, -13, -13, 19, -11, -6, 15, 13, -15, -3, 12, -18, -13, -1, 12, 19, 14, -16, -12, 9, 3, -1, -11, -8, -2, 19, 3, 8, -9, 5, 12, -17, 0, -10, 0, -14, 0, 14, 11, 2, 18, 9, 15, -10, -8, 7, -12, 6, 5, 0, 14, -13, 15, -4, 7, -19, 10, -4, -7, 1, -17, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,156 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0096548404544591904, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.34098899364471436, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.23780135810375214, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,6 } };
const TfArray<1, float> quant9_scale = { 1, { 0.73299676179885864, } };
const TfArray<1, int> quant9_zero = { 1, { 45 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 156, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 160), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1101765_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1101765_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1101765_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1101765_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1101765_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
